### ISSUE TITLE
docker: Investigate using separate networks for services

### ISSUE THREAD

**Issue by ghost** [MbinOrg/mbin#1073]
**Is your feature request related to a problem? Please describe.**

In the code review for the new docker / docker compose setup, it was suggested to use separate networks for the `php` services ([see comment](https://github.com/MbinOrg/mbin/pull/1021#discussion_r1729951721)).

**Describe the solution you'd like**

Investigate if and how the services can be split into different networks. The `www` service should be externally accessible ( and maybe `rabbitmq` too?). The rest should be able to be shield off and only use the internal network.

**Describe alternatives you've considered**

N/A

**Additional context**

See [docker compose networking documentation](https://docs.docker.com/compose/networking/)

**Comment by melroy89** [comment]
I think it's a must have to make this part of https://github.com/MbinOrg/mbin/pull/1085.

So I will try to make this part of that PR and interoperate the changes there. Since if you expose all the ports to the external network it will interfere with existing services like PostgreSQL on the host machine. etc..
