### ISSUE TITLE
Improve the UX of searching for a URL

### ISSUE THREAD

**Issue by KaKi87** [MbinOrg/mbin#1195]
**Is your feature request related to a problem? Please describe.**
Remote posts can be unavailable locally.

**Describe the solution you'd like**
Fetch posts when searched by URL.

**Describe alternatives you've considered**
None

**Additional context**
Cf. [`Kbin/kbin-core@codeberg.org#497`](https://codeberg.org/Kbin/kbin-core/issues/497)

---
Thanks

**Comment by BentiGorlich** [comment]
Hi there, this is already implemented. With some lemmy instances it just won't work because they don't let anyone fetch the data if it was not sent to them, but generally it works just fine. 
However the process is a bit in-transparent. When you search for a url the server will look in the db if we already know of a post with that url. If that is not the case, then the server will put a job in the queue to fetch the post on that url. That is done in the background. So your search result will look empty, when the server is actually getting the post. If you refresh the page ~5 minutes later, the post will be there...

I get that this is not a good UX, so if you want you can rephrase this issue to improve the UX of searching for a URL

**Comment by KaKi87** [comment]
> this is already implemented

Oh, nice, then I'd like to suggest adding that to the list of unique features in the README (or did I miss the related PR ?).

> your search result will look empty, when the server is actually getting the post. If you refresh the page ~5 minutes later, the post will be there...
>
> I get that this is not a good UX

Yeah, it would be nice to have the usual Fediverse experience, i.e. fetch and return at search.

> rephrase this issue to improve the UX of searching for a URL

Will do.

**Comment by BentiGorlich** [comment]
> Oh, nice, then I'd like to suggest adding that to the list of unique features in the README (or did I miss the related PR ?).

I don't think that this is special to mbin, but kbin is dead anyways, so maybe it is time to just list what we can do in the readme and website and not what differentiates us from kbin anymore...

**Comment by KaKi87** [comment]
> I don't think that this is special to mbin

But Kbin doesn't have this feature, as you can see per the issue I linked.

**Comment by BentiGorlich** [comment]
hmm... @melroy89 what do you think?

**Comment by melroy89** [comment]
I would like to see the readme getting a refresh anyways, so yes please. 

The readme should maybe be also be more  focused about what Mbin can do in general, since there are a lot of people who didn't knew about kbin at all. So listing the some generic features Mbin can do (as if you would be new to activitypub) would be very helpful. But also these search features mentioned here.

@KaKi87 Feel free to extend the feature list. Remove 

```
Tons of [GUI improvements](https://github.com/MbinOrg/mbin/pulls?q=is%3Apr+is%3Amerged+label%3Afrontend)
    A lot of [enhancements](https://github.com/MbinOrg/mbin/pulls?q=is%3Apr+is%3Amerged+label%3Aenhancement)
    Various [bug fixes](https://github.com/MbinOrg/mbin/pulls?q=is%3Apr+is%3Amerged+label%3Abug)
```

And replace it with a list of features that make senses for newcomers. You can create a PR.

**Comment by KaKi87** [comment]
> Feel free to extend the feature list

Oh I have no idea, I don't know much about UX 😅

**Comment by melroy89** [comment]
> > Feel free to extend the feature list
> 
> Oh I have no idea, I don't know much about UX 😅

I mean extend the readme (markdown) text.

**Comment by KaKi87** [comment]
> I mean extend the readme (markdown) text.

Yes, but I don't know much about how to do that, as in choosing the items and doing the wording, which is a part of UX design.
