### ISSUE TITLE
Improvements for subscriber box

### ISSUE THREAD

**Issue by TheVillageGuy** [MbinOrg/mbin#154]
A few ideas for the new subscriber box as discussed on matrix

> <@thevillageguy:matrix.org> Or, even better, now that's still new and users haven't gotten used to it yet in it's current form;
> turn it on by default, including for existing users,
> by default seperate,
> Give it a move button (An arrow point to the other size of the screen)
> Give it a close button

>I thought about turning it on by default, but not in the separate layout. >Worth an issue as well

So my final thoughts,

On by default
Give it a pop out button
Once popped out, give it a button to move to other side

I think it will be much appreciated, so a hide button should not necessary

**Comment by melroy89** [comment]
Also discussed on matrix, several contributors of this project might find the main content getting squashed too much when this sidebar is enabled (by default).

If we enable this by default my proposal would be to:

- decrease the width of the subscribers side panel (crop text of magazine names they are too long) 
- increase the total width of the main site content, but still having enough margin left and right. 

Overall I like the idea but at the same time I'm in bit in doubt. Especially since there are also ideas of removing the footer completely. This may or may not interfere with this proposal, depending on the implementation of all this.

**Comment by BentiGorlich** [comment]
What do you think about this @melroy89 :
![grafik](https://github.com/MbinOrg/mbin/assets/25664458/e26686bc-2a67-446b-857d-0aedb266f723)

This sub sidebar is hald the size, I removed the placeholder, beacuse there is not enough space to have them and I tested it with the longest allowed magazine name. I don't know whether a long name should be clipped or not (I'd have to google how to do that), but I tried it without it at first

**Comment by BentiGorlich** [comment]
And regarding the size of the inline sub box: I think there should be a toggle that switches between large and small and the default is small which would be half the size it is now. 
Maybe all the subsripction sidebar settings should go into a new category for them :sweat_smile:

**Comment by TheVillageGuy** [comment]
The size is also dependent on the a amount of subscriptions one has, so a
better solution for a size option would be the amount of subscriptions
visible

**Comment by BentiGorlich** [comment]
Nono, I mean the inline box and that is fixed to `40em;` atm. I think that is what melroy meant as well. The size of it if its is separate depends on the amount of your subscriptions up to a limit of 50. And I don't think that this limit should be increased, or user controlled at all.

**Comment by melroy89** [comment]
@TheVillageGuy you also removed the issue template here. We have a template for a reason..
