### ISSUE TITLE
Magazine threads posted externally do not federate until interacted with. 

### ISSUE THREAD

**Issue by chris-y** [MbinOrg/mbin#351]
**Describe the bug**
Scenario: a magazine "M" is hosted on mbin.
User "A" on an external instance (specifically Lemmy, I'm unsure if this also happens when this external user is also on mbin) posts a thread to magazine M.
User "B" on a different external instance cannot see user A's new thread.

**On which Mbin instance did you find the bug?**
Fedia.io

**To Reproduce**
1. Go to a Lemmy instance
2. Post a thread to an Mbin magazine
3. Go to the Mbin server and observe the post is visible
4. Go to a second Lemmy instance and observe the post is not visible
5. Go back to Mbin and upvote the post
6. The post is now visible on the second Lemmy instance

**Expected behavior**
At step 4 the post should already be visible without following step 5

**Additional context**
This is an old Kbin bug, my original report is here: https://codeberg.org/Kbin/kbin-core/issues/875

**Comment by BentiGorlich** [comment]
I have spend a few hours looking at the code and debugging the issue. However the result is disappointing at best: currently lemmy users cannot subscribe to magazines on anything other than lemmy. I do now know if it always has been this way, however it is currently just not working from the lemmy side (tested with the docker image BE-0.18.5). Only servers with at least one local user subscribed to a remote magazines gets the updates.
I did test it on a live server as well (feddit.de (lemmy 0.19) and gehirneimer.de (mBin)) and the result was the same. I only ever get to see the yellow "subscription pending" button. That button is not going to go away, since lemmy never sends the subscription request. I will create an issue in the lemmy repo as well

**Comment by BentiGorlich** [comment]
@melroy89 @asdfzdfj @e-five256 FYI

**Comment by Nutomic** [comment]
@BentiGorlich Did you check the activities which are being sent during subscription? Specifically there should be a `Follow` activity sent from Lemmy to Mbin, and then an `Accept` activity sent back. [Here](https://github.com/LemmyNet/lemmy/tree/main/crates/apub/assets/lemmy/activities/following) you can see what they look like. If its stuck at pending, it means one of those activities is not getting sent/delivered successfully.

**Comment by BentiGorlich** [comment]
I did and there was nothing beeing sent. However maybe I made a mistake setting the logging it up, I did not see any federation logging, even when some federation requests were being made to beehaw (testing). 
When trying to follow an mBin magazine I saw a lot of queries to `/api/v3/site` (iirc) which is a lemmy specific thing which of course errored when requesting it from mBin (saw it in the mBin logs). My guess is that this call failing causes the `Follow` activity to not being sent. I may of course be mistaken, though

**Comment by BentiGorlich** [comment]
I did not see any inbound activites from lemmy to mbin during testing (and with that I am sure that I setup the logging correctly :D)

**Comment by Nutomic** [comment]
Federation has nothing to do with `/api/v3/site` or any other api endpoints. I just tested following `https://fedia.io/m/firefox` from voyager.lemmy.ml and Lemmy is sending the follow request to the shared inbox at https://fedia.io/f/inbox. However there is no `Accept` response. Maybe shared inbox is not working in mbin, or the Follow/Accept activities are somehow incompatible?

**Comment by BentiGorlich** [comment]
Thanks, greatly appreciate it :)

**Comment by BentiGorlich** [comment]
@Nutomic Its weird... sometimes Lemmy sends out the federation request, and when it does it is working. However the Lemmy instance I set up a few days ago did not work. I set up a second one on a different machine and that one worked instantly. So when the Lemmy instance is sending out the follow request we do send out the accept. So I really don't know what the cause is

**Comment by phiresky** [comment]
Just fyi lemmy had (or possibly still has) a general [outgoing federation bug](https://github.com/LemmyNet/lemmy/issues/4288) in 0.19.0 that might affect the results you get for lemmy instances on 0.19.0

**Comment by BentiGorlich** [comment]
Thanks for the heads up, but I am running 0.18.5. Is that version affected, too?

**Comment by phiresky** [comment]
no, then it's unrelated i guess

**Comment by Nutomic** [comment]
Im not aware of any problem in 0.18.x where activities wouldnt be sent out. You can run Lemmy with env var `RUST_LOG=info,activitypub_federation=debug` to get additional logs. Also be aware that there is a queue for outgoing activities, so sending might be delayed for a bit.

**Comment by BentiGorlich** [comment]
I had the env var on for additional logging, so I would have seen logging output for it, but there was none. Since it was a local test instance I doubt that there was anything going on there that would delay the sending...
However as the issue with lemmy not sending it is not related to this one, I'd prefer to continue talking about it in the issue I created in the Lemmy repo :)
