### ISSUE TITLE
Make it easier to add profile picture

### ISSUE THREAD

**Issue by TheVillageGuy** [MbinOrg/mbin#69]
To change the profile picture you now have to go through settings -> profile, though intuitively people go directly to profile, where it can't be changed.

Either add an edit profile button there, or add an edit profile option to the top right user menu that brings you straight to settings->profile (my preference)

Issue opened 3 weeks ago on codeberg

**Comment by simonrcodrington** [comment]
Yeah this one is a bit confusing. The /profile link makes sense because when you go to someone else's profile, you expect to see all of their posts etc.

But when you're logged in, you kinda assume that if you press profile it would take you to your admin profile edit page under settings (why would you want to view your regular front end facing /profile link if you're in that menu?)

I think maybe changing the wording or adding better links here might clarify what's going on? Maybe even rename *profile* to *view profile* and add a new *edit profile* link also? Thoughts on what we can do here?

**Comment by e-five256** [comment]
Definitely super common in my experience for clicking on your own avatar on your own profile page to bring you to the place to change it (can even do so here on github), so I feel like that seems to make sense UI/UX wise
